sudo: false

matrix:
  include:
    - language: php
      php: 5.6
      env:
        - SYMFONY_VERSION=2.8.*

    - language: php
      php: 5.6
      env:
        - SYMFONY_VERSION=3.4.*

    - language: php
      php: 7.1
      env:
        - SYMFONY_VERSION=2.8.*

    - language: php
      php: 7.1
      env:
        - SYMFONY_VERSION=3.4.*

    - language: php
      php: 7.1
      env:
        - SYMFONY_VERSION=4.0.*

    - language: php
      php: 7.1
      env:
        - SYMFONY_VERSION=dev-master
  allow_failures:
    - env: SYMFONY_VERSION=dev-master

before_script:
  - phpenv config-add travis.php.ini
  - composer self-update
  - composer require symfony/symfony:${SYMFONY_VERSION}
  - vendor/symfony-cmf/testing/bin/travis/phpcr_odm_doctrine_dbal.sh

script: vendor/bin/phpunit
